/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/access-lists': RouteRecordInfo<
      '/access-lists',
      '/access-lists',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/api-keys': RouteRecordInfo<
      '/api-keys',
      '/api-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/audit': RouteRecordInfo<
      '/audit',
      '/audit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/automation/': RouteRecordInfo<
      '/automation/',
      '/automation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/backups': RouteRecordInfo<
      '/backups',
      '/backups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/cities': RouteRecordInfo<
      '/community/cities',
      '/community/cities',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/teleport': RouteRecordInfo<
      '/community/teleport',
      '/community/teleport',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/votes': RouteRecordInfo<
      '/community/votes',
      '/community/votes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/console-logs': RouteRecordInfo<
      '/console-logs',
      '/console-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/accounts': RouteRecordInfo<
      '/economy/accounts',
      '/economy/accounts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/achievement-online-rewards': RouteRecordInfo<
      '/economy/achievement-online-rewards',
      '/economy/achievement-online-rewards',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/daily-reward': RouteRecordInfo<
      '/economy/daily-reward',
      '/economy/daily-reward',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/redeem-codes': RouteRecordInfo<
      '/economy/redeem-codes',
      '/economy/redeem-codes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/reward-operations': RouteRecordInfo<
      '/economy/reward-operations',
      '/economy/reward-operations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/reward-packages': RouteRecordInfo<
      '/economy/reward-packages',
      '/economy/reward-packages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/shop': RouteRecordInfo<
      '/economy/shop',
      '/economy/shop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/transactions': RouteRecordInfo<
      '/economy/transactions',
      '/economy/transactions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-chat/colored': RouteRecordInfo<
      '/game-chat/colored',
      '/game-chat/colored',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-chat/history': RouteRecordInfo<
      '/game-chat/history',
      '/game-chat/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-chat/live': RouteRecordInfo<
      '/game-chat/live',
      '/game-chat/live',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-chat/mutes': RouteRecordInfo<
      '/game-chat/mutes',
      '/game-chat/mutes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-chat/settings': RouteRecordInfo<
      '/game-chat/settings',
      '/game-chat/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-resources': RouteRecordInfo<
      '/game-resources',
      '/game-resources',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/integrations/discord': RouteRecordInfo<
      '/integrations/discord',
      '/integrations/discord',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/integrations/geoip': RouteRecordInfo<
      '/integrations/geoip',
      '/integrations/geoip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mods': RouteRecordInfo<
      '/mods',
      '/mods',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/modules': RouteRecordInfo<
      '/modules',
      '/modules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/permissions': RouteRecordInfo<
      '/permissions',
      '/permissions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/players': RouteRecordInfo<
      '/players',
      '/players',
      Record<never, never>,
      Record<never, never>,
      | '/players/history/'
      | '/players/history/[crossplatformId]'
      | '/players/map'
      | '/players/profile/[crossplatformId]'
    >,
    '/players/history/': RouteRecordInfo<
      '/players/history/',
      '/players/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/players/history/[crossplatformId]': RouteRecordInfo<
      '/players/history/[crossplatformId]',
      '/players/history/:crossplatformId',
      { crossplatformId: ParamValue<true> },
      { crossplatformId: ParamValue<false> },
      | never
    >,
    '/players/map': RouteRecordInfo<
      '/players/map',
      '/players/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/players/profile/[crossplatformId]': RouteRecordInfo<
      '/players/profile/[crossplatformId]',
      '/players/profile/:crossplatformId',
      { crossplatformId: ParamValue<true> },
      { crossplatformId: ParamValue<false> },
      | never
    >,
    '/schedules': RouteRecordInfo<
      '/schedules',
      '/schedules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server-configuration': RouteRecordInfo<
      '/server-configuration',
      '/server-configuration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/world-tools': RouteRecordInfo<
      '/world-tools',
      '/world-tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/access-lists.vue': {
      routes:
        | '/access-lists'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/api-keys.vue': {
      routes:
        | '/api-keys'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/audit.vue': {
      routes:
        | '/audit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/automation/index.vue': {
      routes:
        | '/automation/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/backups.vue': {
      routes:
        | '/backups'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/community/cities.vue': {
      routes:
        | '/community/cities'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/community/teleport.vue': {
      routes:
        | '/community/teleport'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/community/votes.vue': {
      routes:
        | '/community/votes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/console-logs.vue': {
      routes:
        | '/console-logs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/accounts.vue': {
      routes:
        | '/economy/accounts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/achievement-online-rewards.vue': {
      routes:
        | '/economy/achievement-online-rewards'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/daily-reward.vue': {
      routes:
        | '/economy/daily-reward'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/redeem-codes.vue': {
      routes:
        | '/economy/redeem-codes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/reward-operations.vue': {
      routes:
        | '/economy/reward-operations'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/reward-packages.vue': {
      routes:
        | '/economy/reward-packages'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/shop.vue': {
      routes:
        | '/economy/shop'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/transactions.vue': {
      routes:
        | '/economy/transactions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-chat/colored.vue': {
      routes:
        | '/game-chat/colored'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-chat/history.vue': {
      routes:
        | '/game-chat/history'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-chat/live.vue': {
      routes:
        | '/game-chat/live'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-chat/mutes.vue': {
      routes:
        | '/game-chat/mutes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-chat/settings.vue': {
      routes:
        | '/game-chat/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-resources.vue': {
      routes:
        | '/game-resources'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/integrations/discord.vue': {
      routes:
        | '/integrations/discord'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/integrations/geoip.vue': {
      routes:
        | '/integrations/geoip'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/mods.vue': {
      routes:
        | '/mods'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/modules.vue': {
      routes:
        | '/modules'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/permissions.vue': {
      routes:
        | '/permissions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/players.vue': {
      routes:
        | '/players'
        | '/players/history/'
        | '/players/history/[crossplatformId]'
        | '/players/map'
        | '/players/profile/[crossplatformId]'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/players/history/index.vue': {
      routes:
        | '/players/history/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/players/history/[crossplatformId].vue': {
      routes:
        | '/players/history/[crossplatformId]'
      views:
        | never
      pathParamNames:
        | 'crossplatformId'
    }
    'src/pages/players/map.vue': {
      routes:
        | '/players/map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/players/profile/[crossplatformId].vue': {
      routes:
        | '/players/profile/[crossplatformId]'
      views:
        | never
      pathParamNames:
        | 'crossplatformId'
    }
    'src/pages/schedules.vue': {
      routes:
        | '/schedules'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/server-configuration.vue': {
      routes:
        | '/server-configuration'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/world-tools.vue': {
      routes:
        | '/world-tools'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
