/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/chat/appearance': RouteRecordInfo<
      '/community/chat/appearance',
      '/community/chat/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/chat/history': RouteRecordInfo<
      '/community/chat/history',
      '/community/chat/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/chat/live': RouteRecordInfo<
      '/community/chat/live',
      '/community/chat/live',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/chat/mutes': RouteRecordInfo<
      '/community/chat/mutes',
      '/community/chat/mutes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/chat/settings': RouteRecordInfo<
      '/community/chat/settings',
      '/community/chat/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/cities': RouteRecordInfo<
      '/community/cities',
      '/community/cities',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/teleport': RouteRecordInfo<
      '/community/teleport',
      '/community/teleport',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/community/votes': RouteRecordInfo<
      '/community/votes',
      '/community/votes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/accounts': RouteRecordInfo<
      '/economy/accounts',
      '/economy/accounts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/commerce/redeem-codes': RouteRecordInfo<
      '/economy/commerce/redeem-codes',
      '/economy/commerce/redeem-codes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/commerce/shop': RouteRecordInfo<
      '/economy/commerce/shop',
      '/economy/commerce/shop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/rewards/achievements': RouteRecordInfo<
      '/economy/rewards/achievements',
      '/economy/rewards/achievements',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/rewards/daily': RouteRecordInfo<
      '/economy/rewards/daily',
      '/economy/rewards/daily',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/rewards/operations': RouteRecordInfo<
      '/economy/rewards/operations',
      '/economy/rewards/operations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/rewards/packages': RouteRecordInfo<
      '/economy/rewards/packages',
      '/economy/rewards/packages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/economy/transactions': RouteRecordInfo<
      '/economy/transactions',
      '/economy/transactions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/automation/rules': RouteRecordInfo<
      '/operations/automation/rules',
      '/operations/automation/rules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/automation/schedules': RouteRecordInfo<
      '/operations/automation/schedules',
      '/operations/automation/schedules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/backups': RouteRecordInfo<
      '/operations/backups',
      '/operations/backups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/configuration': RouteRecordInfo<
      '/operations/configuration',
      '/operations/configuration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/console': RouteRecordInfo<
      '/operations/console',
      '/operations/console',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/extensions/mods': RouteRecordInfo<
      '/operations/extensions/mods',
      '/operations/extensions/mods',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/extensions/modules': RouteRecordInfo<
      '/operations/extensions/modules',
      '/operations/extensions/modules',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/server': RouteRecordInfo<
      '/operations/server',
      '/operations/server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/operations/world': RouteRecordInfo<
      '/operations/world',
      '/operations/world',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/players/': RouteRecordInfo<
      '/players/',
      '/players',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/players/access-lists': RouteRecordInfo<
      '/players/access-lists',
      '/players/access-lists',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/players/history/': RouteRecordInfo<
      '/players/history/',
      '/players/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/players/history/[crossplatformId]': RouteRecordInfo<
      '/players/history/[crossplatformId]',
      '/players/history/:crossplatformId',
      { crossplatformId: ParamValue<true> },
      { crossplatformId: ParamValue<false> },
      | never
    >,
    '/players/map': RouteRecordInfo<
      '/players/map',
      '/players/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/players/profile/[crossplatformId]': RouteRecordInfo<
      '/players/profile/[crossplatformId]',
      '/players/profile/:crossplatformId',
      { crossplatformId: ParamValue<true> },
      { crossplatformId: ParamValue<false> },
      | never
    >,
    '/players/resources': RouteRecordInfo<
      '/players/resources',
      '/players/resources',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/access': RouteRecordInfo<
      '/system/access',
      '/system/access',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/api-keys': RouteRecordInfo<
      '/system/api-keys',
      '/system/api-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/audit': RouteRecordInfo<
      '/system/audit',
      '/system/audit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/integrations/discord': RouteRecordInfo<
      '/system/integrations/discord',
      '/system/integrations/discord',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/integrations/geoip': RouteRecordInfo<
      '/system/integrations/geoip',
      '/system/integrations/geoip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/community/chat/appearance.vue': {
      routes:
        | '/community/chat/appearance'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/community/chat/history.vue': {
      routes:
        | '/community/chat/history'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/community/chat/live.vue': {
      routes:
        | '/community/chat/live'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/community/chat/mutes.vue': {
      routes:
        | '/community/chat/mutes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/community/chat/settings.vue': {
      routes:
        | '/community/chat/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/community/cities.vue': {
      routes:
        | '/community/cities'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/community/teleport.vue': {
      routes:
        | '/community/teleport'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/community/votes.vue': {
      routes:
        | '/community/votes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/accounts.vue': {
      routes:
        | '/economy/accounts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/commerce/redeem-codes.vue': {
      routes:
        | '/economy/commerce/redeem-codes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/commerce/shop.vue': {
      routes:
        | '/economy/commerce/shop'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/rewards/achievements.vue': {
      routes:
        | '/economy/rewards/achievements'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/rewards/daily.vue': {
      routes:
        | '/economy/rewards/daily'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/rewards/operations.vue': {
      routes:
        | '/economy/rewards/operations'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/rewards/packages.vue': {
      routes:
        | '/economy/rewards/packages'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/economy/transactions.vue': {
      routes:
        | '/economy/transactions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/automation/rules.vue': {
      routes:
        | '/operations/automation/rules'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/automation/schedules.vue': {
      routes:
        | '/operations/automation/schedules'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/backups.vue': {
      routes:
        | '/operations/backups'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/configuration.vue': {
      routes:
        | '/operations/configuration'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/console.vue': {
      routes:
        | '/operations/console'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/extensions/mods.vue': {
      routes:
        | '/operations/extensions/mods'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/extensions/modules.vue': {
      routes:
        | '/operations/extensions/modules'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/server.vue': {
      routes:
        | '/operations/server'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/operations/world.vue': {
      routes:
        | '/operations/world'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/players/index.vue': {
      routes:
        | '/players/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/players/access-lists.vue': {
      routes:
        | '/players/access-lists'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/players/history/index.vue': {
      routes:
        | '/players/history/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/players/history/[crossplatformId].vue': {
      routes:
        | '/players/history/[crossplatformId]'
      views:
        | never
      pathParamNames:
        | 'crossplatformId'
    }
    'src/pages/players/map.vue': {
      routes:
        | '/players/map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/players/profile/[crossplatformId].vue': {
      routes:
        | '/players/profile/[crossplatformId]'
      views:
        | never
      pathParamNames:
        | 'crossplatformId'
    }
    'src/pages/players/resources.vue': {
      routes:
        | '/players/resources'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/access.vue': {
      routes:
        | '/system/access'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/api-keys.vue': {
      routes:
        | '/system/api-keys'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/audit.vue': {
      routes:
        | '/system/audit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/integrations/discord.vue': {
      routes:
        | '/system/integrations/discord'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/system/integrations/geoip.vue': {
      routes:
        | '/system/integrations/geoip'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
