/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/access-lists': RouteRecordInfo<
      '/access-lists',
      '/access-lists',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/api-keys': RouteRecordInfo<
      '/api-keys',
      '/api-keys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/console-logs': RouteRecordInfo<
      '/console-logs',
      '/console-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-chat/colored': RouteRecordInfo<
      '/game-chat/colored',
      '/game-chat/colored',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-chat/history': RouteRecordInfo<
      '/game-chat/history',
      '/game-chat/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-chat/live': RouteRecordInfo<
      '/game-chat/live',
      '/game-chat/live',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/game-chat/settings': RouteRecordInfo<
      '/game-chat/settings',
      '/game-chat/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mods': RouteRecordInfo<
      '/mods',
      '/mods',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/permissions': RouteRecordInfo<
      '/permissions',
      '/permissions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/players': RouteRecordInfo<
      '/players',
      '/players',
      Record<never, never>,
      Record<never, never>,
      | '/players/history/'
      | '/players/history/[crossplatformId]'
      | '/players/map'
    >,
    '/players/history/': RouteRecordInfo<
      '/players/history/',
      '/players/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/players/history/[crossplatformId]': RouteRecordInfo<
      '/players/history/[crossplatformId]',
      '/players/history/:crossplatformId',
      { crossplatformId: ParamValue<true> },
      { crossplatformId: ParamValue<false> },
      | never
    >,
    '/players/map': RouteRecordInfo<
      '/players/map',
      '/players/map',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server-configuration': RouteRecordInfo<
      '/server-configuration',
      '/server-configuration',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/access-lists.vue': {
      routes:
        | '/access-lists'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/api-keys.vue': {
      routes:
        | '/api-keys'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/console-logs.vue': {
      routes:
        | '/console-logs'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-chat/colored.vue': {
      routes:
        | '/game-chat/colored'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-chat/history.vue': {
      routes:
        | '/game-chat/history'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-chat/live.vue': {
      routes:
        | '/game-chat/live'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/game-chat/settings.vue': {
      routes:
        | '/game-chat/settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/mods.vue': {
      routes:
        | '/mods'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/permissions.vue': {
      routes:
        | '/permissions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/players.vue': {
      routes:
        | '/players'
        | '/players/history/'
        | '/players/history/[crossplatformId]'
        | '/players/map'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/players/history/index.vue': {
      routes:
        | '/players/history/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/players/history/[crossplatformId].vue': {
      routes:
        | '/players/history/[crossplatformId]'
      views:
        | never
      pathParamNames:
        | 'crossplatformId'
    }
    'src/pages/players/map.vue': {
      routes:
        | '/players/map'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/server-configuration.vue': {
      routes:
        | '/server-configuration'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
