<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LSTY.SevenDPanel.Adapters.Local</AssemblyName>
    <RootNamespace>LSTY.SevenDPanel.Adapters.Local</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="MaxMind.GeoIP2" Version="6.1.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Net.Http" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(SevenDaysManagedDirectory)\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <ProjectReference Include="..\..\Core\LSTY.SevenDPanel.Application\LSTY.SevenDPanel.Application.csproj" />
    <ProjectReference Include="..\..\Core\LSTY.SevenDPanel.Domain\LSTY.SevenDPanel.Domain.csproj" />
  </ItemGroup>
</Project>
